#server:
#  port: 8888
#
#spring:
#  cloud:
#    config:
#      server:
#        git:
#          uri: "https://github.com/this-is-thiru/spring-external-configs.git"
#          repos:
#            development:
#              uri: "https://github.com/this-is-thiru/spring-external-configs.git"
#              pattern: "*development*"
#              search-paths:
#                - "{profile}"
#                - "common"
#                - "{profile}/*"
#
#  application:
#    name: "spring-config-server"
#
#management:
#  endpoints:
#    web:
#      exposure:
#        include: "*"
#
#

server:
  port: 8888

spring:
  cloud:
    config:
      server:
        git:
          uri: "https://github.com/this-is-thiru/spring-external-configs.git"
          repos:
            development:
              uri: "https://github.com/this-is-thiru/spring-external-configs.git"
              pattern: "*" # Allow all files
              search-paths:
                - "{profile}"
                - "common"
                - "{profile}/*"
                - "/" # search the root of the repository.

  application:
    name: "spring-config-server"

management:
  endpoints:
    web:
      exposure:
        include: "*"